---
title: "Adaptive Designs and Multiple Testing Workshop - 2016"
deadline_submit: "February 29, 2016"
deadline_dinner: "March 13, 2016"
deadline_tour: "March 13, 2016"
begin_workshop: "April 28, 2016"
end_workshop: "April 29, 2016"
---